listening-port=3478

tls-listening-port=5349

fingerprint

use-auth-secret

static-auth-secret=SecureCommSecret

realm=securecomm.local

total-quota=100

bps-capacity=0

stale-nonce

no-loopback-peers

no-multicast-peers

simple-log

log-file=stdout

min-port=49152
max-port=49200

verbose
